[package]
name = "docx-cc"
version = "0.2.0"
edition = "2021"

[dependencies]
pretty_assertions = "1.4.0"
quick-xml = "0.30.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
zip = "0.6.6"

[dev-dependencies]
tempfile = "3.8.1"
