[package]
name = "baserow-cc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
dioxus = "0.4.0"
dioxus-liveview = { version = "0.4.0", features = ["axum"] }
tokio = { version = "1.33.0", features = ["full"] }
